url: "http://jaredcounts.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jared Counts" # the name of your site, e.g. ACME Corp.

markdown: CommonMark
commonmark:
    options: ["UNSAFE", "SMART"]

assets:
  sources:
    - _assets/css
    - _assets/js
    - _assets/image/lightbox
    - _assets/pics
    - _assets/thumbnails
    - _assets/favicons
    - _assets/files

collections:
    pages:
      output: true
      permalink: /:path/
    demos:
      output: true
      permalink: /:path/demo